### PR TITLE
Check for Missing Module

### PR DESCRIPTION
**Pull request by IanMitchell**
Checks for an additional error code per [Node.js spec](https://nodejs.org/api/errors.html#errors_err_missing_module)

### CODE REVIEW

**Comment by sergiodxa** [comment]
That error is for missing ESModules while importing a `.mjs` file. But the module is using `.js` files not `.mjs` files. I don't think we can see that error code.

**Comment by IanMitchell** [comment]
I was able to get it while using this module - https://www.npmjs.com/package/@std/esm. Figured a few other conversion tools might throw it too, but haven't tried others

**Comment by sergiodxa** [comment]
@IanMitchell did you configured `@std/esm` to treat every JS file as ESM?

**Comment by IanMitchell** [comment]
I don't think so - I have this:

```json
  "@std/esm": {
    "esm": "js",
    "cjs": true
  }
```

**Comment by leo** [comment]
Better be safe than sorry!

**Comment by IanMitchell** [comment]
Thanks, appreciate it 😄

**Pull request merged**
