### PR TITLE
Support custom path to local config

### PR DESCRIPTION
**Pull request by tylersnyder**
Similar to Issue #10, I needed a way to pass a custom path to my local config json. I've added an options object and passed options.path along to loadNowJSON.

If accepted this would change usage from 
```
require('now-env')
```

To 
```
require('now-env')()
```

or with a custom path

```
require('now-env')({
    path: './now.dev.json'
})
```

### CODE REVIEW

**Comment by benatkin** [comment]
I suggest using an environment variable to declare the location of `now.json` so an API change isn't needed.

**Comment by tylersnyder** [comment]
@benatkin thank you. I've changed this to check for a `NOW_PATH` environment variable before defaulting to `'./now.json'`.

**Comment by benatkin** [comment]
@tylersnyder @sergiodxa I suggest naming it `NOW_CONFIG` - I think that jibes better with how `now --help` describes it:

```
    -A FILE, --local-config=FILE   Path to the local `now.json` file
```

I think with the announcement of documentation on deploying to now with Travis CI on twitter today that this may be desired for now itself, so Zeit might want to have some say in it. :)

**Comment by benatkin** [comment]
@tylersnyder @sergiodxa sorry if my suggestion of changing `NOW_PATH` to `NOW_CONFIG` delayed this being merged. @sergiodxa maybe you can merge @tylersnyder's PR first and then edit `NOW_PATH` to `NOW_CONFIG` before publishing it.

**Comment by benatkin** [comment]
I can really use this change.

**Comment by sergiodxa** [comment]
I like the way to solve this, thanks for the PR, @benatkin I also like NOW_CONFIG more, will change it after the merge.

**Pull request merged**
